/********************************************************************/
/*			CODE GENERATED BY SHORTHAND GRAPHICS MODULE				*/
/*		   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^			*/
/*									                                */
/*           ________     ____      ____        _________           */
/*			/ _______\    |  |\     |  |\      /  ___  \ \          */
/*         / /\_______\	  |	 | |    |  | |    /  / __\  \ \         */
/*  	  / /_/_______    |  |_|____|  | |   |  / /   \__\/         */
/*		  \________  /\   |   ______   | |   |  | |                 */
/*		   \______/ / /   |  |\_____|  | |   |  | |    ___          */
/*		 ________/ / /    |  | |    |  | |    \  \|___/  /\         */
/*		 \________/ /     |__| |    |__| |     \________/ /         */
/*		  \_______\/       \__\|     \__\|      \_______\/			*/
/*			                                                        */
/*             A Project by Thumssy, Swetha and Sruthy				*/
/*																	*/
/********************************************************************/

#include<graphics.h>
#include<string.h>
#include<stdio.h>
#include<dos.h>

int totimg=0;
char pname[20];

struct ppty{
    int ptype,x1,x2,y1,y2,r,border,start,stop;
	int mover,mclick;
	char name[20],id[5],type[20];
}p[100];

int ncords=0,nf[5000][2];


void init()
	{
	strcpy(pname,"q");
	totimg=2;

	strcpy(p[0].type,"rectangle");
	p[0].ptype=1;
	strcpy(p[0].id,"r0");
	p[0].border=14;
	p[0].x1=111;		p[0].x2=377;
	p[0].y1=163;		p[0].y2=384;
	p[0].start=0;
	p[0].stop=0;
	p[0].mover=0;	p[0].mclick=0;
	
	strcpy(p[1].type,"circle");
	p[1].ptype=2;
	strcpy(p[1].id,"c0");
	p[1].border=14;
	p[1].x1=480;	p[1].y1=237;
	p[1].r=175;
	p[1].start=0;
	p[1].stop=0;
	p[1].mover=0;	p[1].mclick=0;
	}

void moverNclick(int x,int y,int c){
	int i=totimg;
	while(i>=0){
		if(p[i].ptype==1){
			if(x>p[i].x1&&x<p[i].x2){
				if(y>p[i].y1&&y<p[i].y2){
					p[i].mover=1;
					if(c==1)
						p[i].mclick=1;
					}
				}
			}
		else if(p[i].ptype==2){
			if((pow((x-p[i].x1),2)-pow((y-p[i].y1),2))<=pow((p[i].r),2)){
				p[i].mover=1;
					if(c==1)
						p[i].mclick=1;
				}
			}
	i--;
	}
}

void mouseposi(int *x,int *y,int *c){
    union REGS in,out;
    in.x.ax=01;
    int86(0x33,&in,&out);
    in.x.ax=03;
    int86(0x33,&in,&out);
    *x=out.x.cx;
    *y=out.x.dx;
    *c=out.x.bx;
}

void display(){
	int i=totimg,j=0;
	while(i>=0)
		{
		setcolor(p[i].border);
		switch(p[i].ptype)
		{
			case 1:
			 rectangle(p[i].x1,p[i].y1,p[i].x2,p[i].y2);
			 break;
			case 2:
			 circle(p[i].x1,p[i].y1,p[i].r);
			 break;
			case 3:
			 line(p[i].x1,p[i].y1,p[i].x2,p[i].y2);
			 break;
			case 4:
			 for(j=p[i].start+1;j<p[i].stop;j++){
				line(nf[j][0],nf[j][1],nf[j+1][0],nf[j+1][1]);
			}
			break;
		}
		i--;
		}
	setcolor(15);
	}

void main(){
    int gd=DETECT,gm;
	int x,y,c,i;
    initgraph(&gd,&gm,"c:\\TurboC3\\BGI");
	init();
	while(!kbhit())
		{
		for(i=0;i<totimg;i++)
			display();
		mouseposi(&x,&y,&c);
		moverNclick(x,y,c);
		}
    getch();
}