

		/*			 Code generated by ShortHand Converter			*
		 *			A Project By Sruthy, Swetha and Thumssy			*/


#include<stdio.h>
#include<stdlib.h>
#include<time.h>

//Start of analyse() 

#define analyse\
  {\
  char* c_time_string;\
  time_t current_time;\
  current_time=time(NULL);\
  c_time_string=ctime(&current_time);\
  printf("\nTime : %s",c_time_string);\
  getch();\
  }\
//End of analyse() 


//Start of test() 


#define test\
	{\
	printf("c = %d\n",c);\
	printf("n = %d\n",n);\
	printf("fact = %d\n",fact);\
	printf("1 = %d\n",1);\
	getch();\
	}
//End of test() 

 
 void main()
{
  int c,n,fact=1;
   analyse
  printf("Enter a number to calculate its factorial : ");
  scanf("%d",&n);
 
  for(c=1;c<=n;c++)
    {
	fact=fact*c;
	test
	}
  printf("\n\nFactorial of %d = %d\n",n,fact);
  analyse
}