

		/*			 Code generated by ShortHand Converter			*
		 *			A Project By Sruthy, Swetha and Thumssy			*/


#include<stdio.h>

//Start of matrixin() 

void matrixin(int *r,int *c,int mat[10][10])
{
int i,j;
printf("\n Enter the number of rows : ");
scanf("%d",&*r);
printf("\n Enter the nummber of columns : ");
scanf("%d",&*c);
printf("\n Enter the elements of the matrix : ");
for(i=0;i<*r;i++)
	{
	for(j=0;j<*c;j++)
		{
		scanf("%d",&mat[i][j]);
		}
	}

}
//End of matrixin() 


//Start of matrixadd() 

void matrixadd(int *m,int *n, int *c,int *d,int first[10][10],int second[10][10],int sum[10][10])
{
int i,j,r1,c1,r2,c2;
r1=*m;
c1=*n;
r2=*c;
c2=*d;
   for ( r2= 0 ; r2 < r1 ; r2++ )
      for ( c2= 0 ; c2< c1 ;c2++ )
         sum[r2][c2] = first[r2][c2] + second[r2][c2];
 
   printf("Sum of entered matrices:-\n");
 
   for ( r2 = 0 ; r2<r1 ;r2++ )
   {
      for ( c2 = 0 ; c2 < c1 ; c2++ )
         printf("%d\t", sum[r2][c2]);
 
      printf("\n");
   }
 
}
//End of matrixadd() 

void main()
{
int r,c,a,b,sum[10][10],mat[10][10],matr[10][10];
matrixin(&r,&c,mat);
matrixin(&a,&b,matr);
matrixadd(&r,&c,&a,&b,mat,matr,sum);
}
